
// # JS Package: syntax-tpl.pak.js :: #START# :: @ generated from lib/js/jshighlight/syntax/tpl/*.js
// Included Files: tpl/*.js #

// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###

// === tpl/markertpl.js

/*
Language: Markers-TPL (Smart.Framework) v.20191115
Requires: xml.js
Author: unix-world.org
Description: Markers-TPL is a templating language for PHP and Javascript built into Smart.Framework
Category: template
*/

// syntax/tpl/markertpl.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('markertpl',
function(hljs) {

	var SYNTAX = 'IF LOOP ELSE';

	return {
		aliases: ['markerstpl','smartframeworktpl'],
		case_insensitive: false,
		subLanguage: 'xml',
		contains: [
			hljs.COMMENT(/\[%%%COMMENT%%%\]/, /\[%%%\/COMMENT%%%\]/),
			{ // syntax: if, loop, specials (space, tab, new line, carriage return, left/right square bracket)
				className: 'meta',
				begin: /\[%%%/, end: /(\([0-9]+\))?%%%\]/,
				contains: [
					{
						className: 'regexp',
						begin: /(\|[A-Z0-9\-]+)/ // {{{SYNC-TPL-EXPR-SPECIALS}}}
					},
					{ // {{{SYNC-TPL-EXPR-IF}}} {{{SYNC-TPL-EXPR-LOOP}}}
						className: 'symbol',
						begin: /([\/\|a-zA-Z0-9_\-\.\:]+)/,
						keywords: SYNTAX
					},
					{ // {{{SYNC-TPL-EXPR-IF}}}
						className: 'regexp', // tag
						end: /((@\=\=|@\!\=|@\<\=|@\<|@\>\=|@\>|\=\=|\!\=|\<\=|\<|\>\=|\>|\!%|%|\!\?|\?|\^~|\^\*|&~|&\*|\$~|\$\*)([^\[\]]*);)?/,
						starts: {
							endsWithParent: true,
							relevance: 0
						}
					}
				]
			},
			{ // sub-template
				className: 'meta',
				begin: /\[@@@/, end: /@@@\]/,
				contains: [
					{
						className: 'keyword',
						begin: /(SUB\-TEMPLATE\:){1}/,
					},
					{ // {{{SYNC-TPL-EXPR-SUBTPL}}}
						className: 'title', // 'regexp'
						begin: /([a-zA-Z0-9_\-\.\/\!\?%]+)/,
					//	returnEnd: true
					},
					{
						className: 'regexp', // 'symbol'
						end: /(\|[a-z0-9]+)*/,
						starts: {
							endsWithParent: true,
							relevance: 0
						}
					}
				]
			},
			{ // markers
				className: 'regexp', // 'template-variable'
				begin: /\[###/, end: /###\]/,
				contains: [
					{
						className: 'keyword',
						begin: /[A-Z0-9_\-\.]+/,
					//	returnEnd: true
					},
					{
						className: 'symbol',
						end: /(\|[a-z0-9]+)*/,
						starts: {
							endsWithParent: true,
							relevance: 0
						}
					}
				]
			}
		]
	};
}
);

// #END

// === tpl/tex.js

/*
Language: TeX
Author: Vladimir Moskva <vladmos@gmail.com>
Website: http://fulc.ru/
Category: markup
*/

// syntax/tpl/tex.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('tex',
function(hljs) {
	var COMMAND = {
		className: 'tag',
		begin: /\\/,
		relevance: 0,
		contains: [
			{
				className: 'name',
				variants: [
					{begin: /[a-zA-Zа-яА-я]+[*]?/},
					{begin: /[^a-zA-Zа-яА-я0-9]/}
				],
				starts: {
					endsWithParent: true,
					relevance: 0,
					contains: [
						{
							className: 'string', // because it looks like attributes in HTML tags
							variants: [
								{begin: /\[/, end: /\]/},
								{begin: /\{/, end: /\}/}
							]
						},
						{
							begin: /\s*=\s*/, endsWithParent: true,
							relevance: 0,
							contains: [
								{
									className: 'number',
									begin: /-?\d*\.?\d+(pt|pc|mm|cm|in|dd|cc|ex|em)?/
								}
							]
						}
					]
				}
			}
		]
	};

	return {
		contains: [
			COMMAND,
			{
				className: 'formula',
				contains: [COMMAND],
				relevance: 0,
				variants: [
					{begin: /\$\$/, end: /\$\$/},
					{begin: /\$/, end: /\$/}
				]
			},
			hljs.COMMENT(
				'%',
				'$',
				{
					relevance: 0
				}
			)
		]
	};
}
);

// #END

// ===== [#]

// # JS Package: syntax-tpl.pak.js :: #END#

