
// # JS Package: syntax-net.pak.js :: #START# :: @ generated from lib/js/jshighlight/syntax/net/*.js
// Included Files: net/*.js #

// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###

// === net/csp.js

/*
Language: CSP
Description: Content Security Policy definition highlighting
Author: Taras <oxdef@oxdef.info>
*/

// syntax/net/csp.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('csp',
function(hljs) {
	return {
		case_insensitive: false,
		lexemes: '[a-zA-Z][a-zA-Z0-9_-]*',
		keywords: {
			keyword: 'base-uri child-src connect-src default-src font-src form-action' +
				' frame-ancestors frame-src img-src media-src object-src plugin-types' +
				' report-uri sandbox script-src style-src',
		},
		contains: [
		{
			className: 'string',
			begin: "'", end: "'"
		},
		{
			className: 'attribute',
			begin: '^Content', end: ':', excludeEnd: true,
		},
		]
	};
}
);

// #END

// === net/http.js

/*
Language: HTTP
Description: HTTP request and response headers with automatic body highlighting
Author: Ivan Sagalaev <maniac@softwaremaniacs.org>
Category: common, protocols
*/

// syntax/net/http.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('http',
function(hljs) {
	var VERSION = 'HTTP/[0-9\\.]+';
	return {
		aliases: ['https'],
		illegal: '\\S',
		contains: [
			{
				begin: '^' + VERSION, end: '$',
				contains: [{className: 'number', begin: '\\b\\d{3}\\b'}]
			},
			{
				begin: '^[A-Z]+ (.*?) ' + VERSION + '$', returnBegin: true, end: '$',
				contains: [
					{
						className: 'string',
						begin: ' ', end: ' ',
						excludeBegin: true, excludeEnd: true
					},
					{
						begin: VERSION
					},
					{
						className: 'keyword',
						begin: '[A-Z]+'
					}
				]
			},
			{
				className: 'attribute',
				begin: '^\\w', end: ': ', excludeEnd: true,
				illegal: '\\n|\\s|=',
				starts: {end: '$', relevance: 0}
			},
			{
				begin: '\\n\\n',
				starts: {subLanguage: [], endsWithParent: true}
			}
		]
	};
}
);

// #END

// ===== [#]

// # JS Package: syntax-net.pak.js :: #END#

