<!-- start FLV Player v.2015.02.15 -->
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,115,0" width="720" height="404" id="unixworld-flv-player" align="middle">
<param name="movie" value="lib/flv-player/unixworld-flv-player.swf">
<param name="flashvars" value="&mov={$ptmp_player_flv}">
<param name="menu" value="false">
<param name="quality" value="high">
<param name="allowFullScreen" value="true">
<param name="SeamlessTabbing" value="false">
<param name="bgcolor" value="#000000">
<embed src="lib/flv-player/unixworld-flv-player.swf" flashvars="&mov={$ptmp_player_flv}" menu="false" quality="high" allowFullScreen="true" SeamlessTabbing="false" bgcolor="#000000" width="720" height="404" name="unixworld-flv-player" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">
</object>
<!-- end FLV Player -->
